package com.cofco.qiqihar.graintrade.supply.interfaceadapter;
import com.cofco.qiqihar.graintrade.shared.application.ClientRequestException;import com.cofco.qiqihar.graintrade.shared.interfaceadapter.ApiResponse;import com.cofco.qiqihar.graintrade.shared.interfaceadapter.StrictQueryParameters;
import com.cofco.qiqihar.graintrade.supply.application.*;import java.math.BigDecimal;import java.util.List;import java.util.Set;import java.util.regex.Pattern;
import org.springframework.util.MultiValueMap;import org.springframework.web.bind.annotation.*;
@RestController public class SupplyAccountController{
 private static final Pattern DECIMAL=Pattern.compile("^-?(?:\\d+(?:\\.\\d*)?|\\.\\d+)$");private final SupplyAccountService service;public SupplyAccountController(SupplyAccountService service){this.service=service;}
 @GetMapping("/api/v1/supply-accounts") ApiResponse<List<SupplyAccountView>> list(@RequestParam MultiValueMap<String,String> params){StrictQueryParameters p=StrictQueryParameters.parse(params,Set.of("productCode","regionCode","marketingYear","resultState","version")::contains,SupplyAccountController::invalid);Integer version=p.optional("version")==null?null:integer(p.optional("version"));return new ApiResponse<>(service.list(p.required("productCode"),p.required("regionCode"),p.required("marketingYear"),p.optional("resultState"),version));}
 @PostMapping("/api/v1/supply-accounts/runs") ApiResponse<SupplyAccountView> run(@RequestBody RunRequest r){return new ApiResponse<>(service.run(r.command()));}
 @PostMapping("/api/v1/supply-sources/releases") ApiResponse<SupplyReleaseView> release(@RequestBody ReleaseRequest r){return new ApiResponse<>(service.release(r.command()));}
 @PostMapping("/api/v1/supply-inputs/manual-decisions") ApiResponse<SupplyReleaseView> manual(@RequestBody ManualRequest r){return new ApiResponse<>(service.approveManual(r.command()));}
 @PostMapping("/api/v1/supply-input-sets") ApiResponse<SupplyInputSetView> inputSet(@RequestBody InputSetRequest r){return new ApiResponse<>(service.createInputSet(r.command()));}
 record RunRequest(String productCode,String regionCode,String marketingYear,String inputSetId,String adjustmentProposalValue,String adjustmentProposalReason,Long expectedDecisionVersion,Boolean publish){SupplyRunCommand command(){if(expectedDecisionVersion==null||expectedDecisionVersion<0||publish==null||adjustmentProposalValue==null||!DECIMAL.matcher(adjustmentProposalValue).matches())throw invalid();return new SupplyRunCommand(productCode,regionCode,marketingYear,inputSetId,new BigDecimal(adjustmentProposalValue),adjustmentProposalReason,expectedDecisionVersion,publish);}}
 record ReleaseRequest(String sourceDomain,String sourceRecordId,Long sourceVersion,String productCode,String regionCode,String marketingYear,
   String roleCode,String sourceFieldCode,String qualityState){UpstreamSourceReleaseCommand command(){if(sourceVersion==null)throw invalid();return new UpstreamSourceReleaseCommand(sourceDomain,sourceRecordId,sourceVersion,productCode,regionCode,marketingYear,roleCode,sourceFieldCode,qualityState);}}
 record ManualRequest(String productCode,String regionCode,String marketingYear,String roleCode,String value,String reason,Long expectedVersion){ManualInputDecisionCommand command(){if(expectedVersion==null||value==null||!DECIMAL.matcher(value).matches())throw invalid();return new ManualInputDecisionCommand(productCode,regionCode,marketingYear,roleCode,new BigDecimal(value),reason,expectedVersion);}}
 record InputSetRequest(String productCode,String regionCode,String marketingYear,String reason,Long expectedVersion,List<InputSetItemRequest> items){SupplyInputSetCommand command(){if(expectedVersion==null)throw invalid();return new SupplyInputSetCommand(productCode,regionCode,marketingYear,reason,expectedVersion,items==null?null:items.stream().map(InputSetItemRequest::item).toList());}}
 record InputSetItemRequest(String roleCode,String sourceReleaseId){SupplyInputSetCommand.Item item(){return new SupplyInputSetCommand.Item(roleCode,sourceReleaseId);}}
 private static int integer(String v){try{return Integer.parseInt(v);}catch(NumberFormatException e){throw invalid();}}
 private static ClientRequestException invalid(){return new ClientRequestException("INVALID_SUPPLY_ACCOUNT_REQUEST","Supply account request is invalid");}
}
