-- Generated by scripts/generate-qiqihar-open-boundaries.py. Do not edit V160 by hand.
-- Source data is open ODbL-1.0 data standardized by geoBoundaries from OpenStreetMap.
-- It is deliberately labelled as non-official and must not be represented as an official survey.

CREATE TABLE overview.administrative_boundary_dataset (
  dataset_id varchar(120) PRIMARY KEY,
  source_name varchar(200) NOT NULL,
  source_owner varchar(200) NOT NULL,
  source_url text NOT NULL,
  source_revision varchar(200) NOT NULL,
  source_build_on date NOT NULL,
  represented_year integer NOT NULL,
  source_crs varchar(40) NOT NULL,
  derived_crs varchar(40) NOT NULL,
  source_license varchar(120) NOT NULL,
  source_license_url text NOT NULL,
  attribution text NOT NULL,
  original_sha256 char(64) NOT NULL,
  derived_sha256 char(64) NOT NULL,
  derivation_method text NOT NULL,
  official_survey boolean NOT NULL DEFAULT false CHECK (NOT official_survey),
  loaded_at timestamptz NOT NULL DEFAULT now()
);

COMMENT ON TABLE overview.administrative_boundary_dataset IS
  'Traceable open-data inputs for administrative boundaries. Rows with official_survey=false must never be presented as official surveying or mapping products.';

ALTER TABLE overview.administrative_boundary
  ADD COLUMN source_dataset_id varchar(120)
  REFERENCES overview.administrative_boundary_dataset(dataset_id);

ALTER TABLE overview.monitoring_scope_boundary
  ALTER COLUMN source_revision TYPE text;

ALTER TABLE overview.monitoring_scope_boundary_render
  ALTER COLUMN source_revision TYPE text;

CREATE TEMP TABLE qiqihar_open_boundary_seed (
  region_code varchar(12) PRIMARY KEY,
  region_name varchar(100) NOT NULL,
  source_feature_name varchar(160) NOT NULL,
  source_feature_id varchar(120) UNIQUE NOT NULL,
  geometry geometry(MultiPolygon,4326) NOT NULL,
  CHECK (ST_IsValid(geometry)),
  CHECK (NOT ST_IsEmpty(geometry)),
  CHECK (ST_SRID(geometry)=4326)
) ON COMMIT DROP;

INSERT INTO qiqihar_open_boundary_seed(
  region_code,region_name,source_feature_name,source_feature_id,geometry)
VALUES
@@BOUNDARY_ROWS@@;

DO $$
DECLARE
  identity_drift text;
  existing_conflicts text;
  invalid_count integer;
  overlap_count integer;
BEGIN
  WITH expected(region_code,region_name,parent_code,administrative_level) AS (
    VALUES
      ('230200','齐齐哈尔市',NULL::varchar,'PREFECTURE'),
      ('230202','龙沙区','230200','COUNTY'),('230203','建华区','230200','COUNTY'),
      ('230204','铁锋区','230200','COUNTY'),('230205','昂昂溪区','230200','COUNTY'),
      ('230206','富拉尔基区','230200','COUNTY'),('230207','碾子山区','230200','COUNTY'),
      ('230208','梅里斯达斡尔族区','230200','COUNTY'),('230221','龙江县','230200','COUNTY'),
      ('230223','依安县','230200','COUNTY'),('230224','泰来县','230200','COUNTY'),
      ('230225','甘南县','230200','COUNTY'),('230227','富裕县','230200','COUNTY'),
      ('230229','克山县','230200','COUNTY'),('230230','克东县','230200','COUNTY'),
      ('230231','拜泉县','230200','COUNTY'),('230281','讷河市','230200','COUNTY')
  )
  SELECT string_agg(expected.region_code || ':' || expected.region_name, ', '
                    ORDER BY expected.region_code)
    INTO identity_drift
    FROM expected
    LEFT JOIN platform.region actual ON actual.code=expected.region_code
   WHERE actual.code IS NULL OR actual.name<>expected.region_name
      OR actual.parent_code IS DISTINCT FROM expected.parent_code
      OR actual.administrative_level<>expected.administrative_level;
  IF identity_drift IS NOT NULL THEN
    RAISE EXCEPTION 'V160 Qiqihar region identity gate failed: %',identity_drift;
  END IF;

  SELECT string_agg(boundary.region_code || ':' || boundary.source_name, ', '
                    ORDER BY boundary.region_code)
    INTO existing_conflicts
    FROM overview.administrative_boundary boundary
   WHERE boundary.region_code IN (
     '230200','230202','230203','230204','230205','230206','230207','230208',
     '230221','230223','230224','230225','230227','230229','230230','230231','230281'
   );
  IF existing_conflicts IS NOT NULL THEN
    RAISE EXCEPTION
      'V160 refuses conflicting Qiqihar administrative boundary: %',
      existing_conflicts;
  END IF;

  SELECT count(*) FILTER(
           WHERE GeometryType(geometry)<>'MULTIPOLYGON'
              OR NOT ST_IsValid(geometry) OR ST_IsEmpty(geometry)
              OR ST_SRID(geometry)<>4326)
    INTO invalid_count
    FROM qiqihar_open_boundary_seed;
  IF (SELECT count(*) FROM qiqihar_open_boundary_seed)<>16 OR invalid_count<>0 THEN
    RAISE EXCEPTION 'V160 source geometry gate failed: expected 16, invalid %',invalid_count;
  END IF;

  SELECT count(*) INTO overlap_count
    FROM qiqihar_open_boundary_seed left_boundary
    JOIN qiqihar_open_boundary_seed right_boundary
      ON right_boundary.region_code>left_boundary.region_code
     AND left_boundary.geometry && right_boundary.geometry
   WHERE ST_Area(ST_Intersection(
           left_boundary.geometry,right_boundary.geometry)::geography)>1;
  IF overlap_count<>0 THEN
    RAISE EXCEPTION 'V160 source geometry overlap gate failed: % pairs',overlap_count;
  END IF;
END;
$$;

INSERT INTO overview.administrative_boundary_dataset(
  dataset_id,source_name,source_owner,source_url,source_revision,source_build_on,
  represented_year,source_crs,derived_crs,source_license,source_license_url,
  attribution,original_sha256,derived_sha256,derivation_method,official_survey)
VALUES(
  'geoboundaries-chn-adm3-9469f09-qiqihar-2017',
  'geoBoundaries gbOpen CHN ADM3',
  'OpenStreetMap contributors and geoBoundaries',
  'https://github.com/wmgeolab/geoBoundaries/tree/9469f09/releaseData/gbOpen/CHN/ADM3',
  'geoBoundaries commit 9469f09','2023-12-12',
  2017,'OGC CRS84','EPSG:4326','ODbL-1.0',
  'https://opendatacommons.org/licenses/odbl/1-0/',
  'Contains information from OpenStreetMap, available under ODbL 1.0; standardized by geoBoundaries. Open source, non-official surveying product.',
  '3cc71d6cd23e7dbb5646422b40dd92a7a74d8779f340eb9377158c961dec310e',
  '@@DERIVED_GEOJSON_SHA256@@',
  'Filter 16 pinned ADM3 feature ids; promote Polygon to MultiPolygon without simplification; derive 230200 as the unary union of all 16 counties.',
  false);

INSERT INTO overview.administrative_boundary(
  region_code,geometry,source_name,source_url,source_revision,source_license,
  source_feature_id,source_effective_on,geometry_sha256,source_dataset_id)
SELECT seed.region_code,seed.geometry,
       'geoBoundaries gbOpen CHN ADM3 (OpenStreetMap source)',
       'https://github.com/wmgeolab/geoBoundaries/tree/9469f09/releaseData/gbOpen/CHN/ADM3',
       '9469f09; build 2023-12-12; represented 2017; exact feature extract',
       'ODbL-1.0; open source; non-official survey product',
       seed.source_feature_id,NULL,
       encode(sha256(ST_AsEWKB(seed.geometry)),'hex'),
       'geoboundaries-chn-adm3-9469f09-qiqihar-2017'
  FROM qiqihar_open_boundary_seed seed;

INSERT INTO overview.administrative_boundary(
  region_code,geometry,source_name,source_url,source_revision,source_license,
  source_feature_id,source_effective_on,geometry_sha256,source_dataset_id)
SELECT '230200',city.geometry,
       'Derived union of 16 geoBoundaries Qiqihar county features',
       'https://github.com/wmgeolab/geoBoundaries/tree/9469f09/releaseData/gbOpen/CHN/ADM3',
       '9469f09; build 2023-12-12; represented 2017; exact county union',
       'ODbL-1.0; open source; non-official survey product',
       'derived-union:230200:16-counties',NULL,
       encode(sha256(ST_AsEWKB(city.geometry)),'hex'),
       'geoboundaries-chn-adm3-9469f09-qiqihar-2017'
  FROM (
    SELECT ST_Multi(ST_UnaryUnion(ST_Collect(geometry)))
             ::geometry(MultiPolygon,4326) geometry
      FROM qiqihar_open_boundary_seed
  ) city;

DO $$
DECLARE
  invalid_count integer;
  uncovered_count integer;
BEGIN
  SELECT count(*) FILTER(
           WHERE GeometryType(geometry)<>'MULTIPOLYGON'
              OR NOT ST_IsValid(geometry) OR ST_IsEmpty(geometry)
              OR ST_SRID(geometry)<>4326
              OR geometry_sha256<>encode(sha256(ST_AsEWKB(geometry)),'hex'))
    INTO invalid_count
    FROM overview.administrative_boundary
   WHERE region_code IN (
     '230200','230202','230203','230204','230205','230206','230207','230208',
     '230221','230223','230224','230225','230227','230229','230230','230231','230281'
   );
  SELECT count(*) INTO uncovered_count
    FROM overview.administrative_boundary child
    JOIN overview.administrative_boundary city ON city.region_code='230200'
   WHERE child.region_code<>'230200'
     AND child.source_dataset_id='geoboundaries-chn-adm3-9469f09-qiqihar-2017'
     AND NOT ST_CoveredBy(child.geometry,city.geometry);
  IF invalid_count<>0 OR uncovered_count<>0 THEN
    RAISE EXCEPTION
      'V160 persisted geometry gate failed: invalid %, uncovered %',
      invalid_count,uncovered_count;
  END IF;
END;
$$;

SELECT overview.refresh_administrative_boundary_render();
SELECT overview.refresh_monitoring_scope_boundary_render('FORMAL_BUSINESS');

COMMENT ON COLUMN overview.administrative_boundary.source_dataset_id IS
  'Traceable source dataset. A non-null value does not imply an official surveying or mapping result.';
