package com.cofco.qiqihar.graintrade.supply.application;
import java.util.List;

public record SupplyAccountView(
        String id,
        String productCode,
        String regionCode,
        String periodCode,
        int surveyYear,
        String surveyQuarter,
        String periodPrecision,
        String marketingYear,
        int resultVersion,
        Integer supersedesResultVersion,
        String calculationChecksum,
        long decisionVersion,
        String resultState,
        String temporalGovernanceState,
        List<String> validationCodes,
        boolean balanced,
        boolean publishable,
        String balanceReason,
        String totalSupply,
        String totalUse,
        String calculatedEndingInventory,
        String approvedAdjustment,
        String adoptedEndingInventory,
        String surveyedEndingInventory,
        String inventoryReconciliationDifference,
        String inputSetId,
        boolean legacyReadOnly,
        SupplyAdjustmentProposalView adjustmentProposal,
        SupplyAdjustmentAuditView adjustmentAudit,
        SupplyFormulaView formula,
        List<SupplySourceView> sources) {}
